openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Dog breeds

paths:
  /dogbreeds/{breedId}:
    parameters:
      - name: breedId
        description: The unique identifier of the dog breed
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/BreedId'
    get:
      summary: Read a dog breed
      responses:
        '200':
          description: The dog breed corresponding to the provided `breedId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dogbreed'
        404:
          description: No dog breed found for the provided `breedId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    BreedId:
      description: The unique identifier of a dog breed
      type: string
    Dogbreed:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/BreedId'
        name:
          type: string
        type:
          type: string
          enum:
            - companion
            - guarding
            - herding
            - hunting
            - working
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []